add_test([=[TestS1.Test1]=]  [==[/Users/Nyamerka/VS Code Projects/C++/OOP/lab5/test]==] [==[--gtest_filter=TestS1.Test1]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[TestS1.Test1]=]  PROPERTIES WORKING_DIRECTORY [==[/Users/Nyamerka/VS Code Projects/C++/OOP/lab5]==] SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Allocator.Vector_push_back]=]  [==[/Users/Nyamerka/VS Code Projects/C++/OOP/lab5/test]==] [==[--gtest_filter=Allocator.Vector_push_back]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Allocator.Vector_push_back]=]  PROPERTIES WORKING_DIRECTORY [==[/Users/Nyamerka/VS Code Projects/C++/OOP/lab5]==] SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Allocator.Vector_deleting_elements]=]  [==[/Users/Nyamerka/VS Code Projects/C++/OOP/lab5/test]==] [==[--gtest_filter=Allocator.Vector_deleting_elements]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Allocator.Vector_deleting_elements]=]  PROPERTIES WORKING_DIRECTORY [==[/Users/Nyamerka/VS Code Projects/C++/OOP/lab5]==] SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Allocator.Vector_changing_elements]=]  [==[/Users/Nyamerka/VS Code Projects/C++/OOP/lab5/test]==] [==[--gtest_filter=Allocator.Vector_changing_elements]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Allocator.Vector_changing_elements]=]  PROPERTIES WORKING_DIRECTORY [==[/Users/Nyamerka/VS Code Projects/C++/OOP/lab5]==] SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Stack.push]=]  [==[/Users/Nyamerka/VS Code Projects/C++/OOP/lab5/test]==] [==[--gtest_filter=Stack.push]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Stack.push]=]  PROPERTIES WORKING_DIRECTORY [==[/Users/Nyamerka/VS Code Projects/C++/OOP/lab5]==] SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Stack.pop]=]  [==[/Users/Nyamerka/VS Code Projects/C++/OOP/lab5/test]==] [==[--gtest_filter=Stack.pop]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Stack.pop]=]  PROPERTIES WORKING_DIRECTORY [==[/Users/Nyamerka/VS Code Projects/C++/OOP/lab5]==] SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Stack.pop_and_push]=]  [==[/Users/Nyamerka/VS Code Projects/C++/OOP/lab5/test]==] [==[--gtest_filter=Stack.pop_and_push]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Stack.pop_and_push]=]  PROPERTIES WORKING_DIRECTORY [==[/Users/Nyamerka/VS Code Projects/C++/OOP/lab5]==] SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Stack.size]=]  [==[/Users/Nyamerka/VS Code Projects/C++/OOP/lab5/test]==] [==[--gtest_filter=Stack.size]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Stack.size]=]  PROPERTIES WORKING_DIRECTORY [==[/Users/Nyamerka/VS Code Projects/C++/OOP/lab5]==] SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Stack.empty]=]  [==[/Users/Nyamerka/VS Code Projects/C++/OOP/lab5/test]==] [==[--gtest_filter=Stack.empty]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Stack.empty]=]  PROPERTIES WORKING_DIRECTORY [==[/Users/Nyamerka/VS Code Projects/C++/OOP/lab5]==] SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Stack.copy_operator]=]  [==[/Users/Nyamerka/VS Code Projects/C++/OOP/lab5/test]==] [==[--gtest_filter=Stack.copy_operator]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Stack.copy_operator]=]  PROPERTIES WORKING_DIRECTORY [==[/Users/Nyamerka/VS Code Projects/C++/OOP/lab5]==] SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Iterator.begin]=]  [==[/Users/Nyamerka/VS Code Projects/C++/OOP/lab5/test]==] [==[--gtest_filter=Iterator.begin]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Iterator.begin]=]  PROPERTIES WORKING_DIRECTORY [==[/Users/Nyamerka/VS Code Projects/C++/OOP/lab5]==] SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Iterator.increment]=]  [==[/Users/Nyamerka/VS Code Projects/C++/OOP/lab5/test]==] [==[--gtest_filter=Iterator.increment]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Iterator.increment]=]  PROPERTIES WORKING_DIRECTORY [==[/Users/Nyamerka/VS Code Projects/C++/OOP/lab5]==] SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Iterator.change_value]=]  [==[/Users/Nyamerka/VS Code Projects/C++/OOP/lab5/test]==] [==[--gtest_filter=Iterator.change_value]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Iterator.change_value]=]  PROPERTIES WORKING_DIRECTORY [==[/Users/Nyamerka/VS Code Projects/C++/OOP/lab5]==] SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ConstIterator.begin]=]  [==[/Users/Nyamerka/VS Code Projects/C++/OOP/lab5/test]==] [==[--gtest_filter=ConstIterator.begin]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ConstIterator.begin]=]  PROPERTIES WORKING_DIRECTORY [==[/Users/Nyamerka/VS Code Projects/C++/OOP/lab5]==] SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ConstIterator.increment]=]  [==[/Users/Nyamerka/VS Code Projects/C++/OOP/lab5/test]==] [==[--gtest_filter=ConstIterator.increment]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ConstIterator.increment]=]  PROPERTIES WORKING_DIRECTORY [==[/Users/Nyamerka/VS Code Projects/C++/OOP/lab5]==] SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set(  test_TESTS TestS1.Test1 Allocator.Vector_push_back Allocator.Vector_deleting_elements Allocator.Vector_changing_elements Stack.push Stack.pop Stack.pop_and_push Stack.size Stack.empty Stack.copy_operator Iterator.begin Iterator.increment Iterator.change_value ConstIterator.begin ConstIterator.increment)
