add_test([=[FourInitialize.Constructor]=]  [==[/Users/Nyamerka/VS Code Projects/C++/OOP/lab2/tests]==] [==[--gtest_filter=FourInitialize.Constructor]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[FourInitialize.Constructor]=]  PROPERTIES WORKING_DIRECTORY [==[/Users/Nyamerka/VS Code Projects/C++/OOP/lab2]==] SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[FourInitize.InitializerListConstructorCorrect]=]  [==[/Users/Nyamerka/VS Code Projects/C++/OOP/lab2/tests]==] [==[--gtest_filter=FourInitize.InitializerListConstructorCorrect]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[FourInitize.InitializerListConstructorCorrect]=]  PROPERTIES WORKING_DIRECTORY [==[/Users/Nyamerka/VS Code Projects/C++/OOP/lab2]==] SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[FourOperators.Plus]=]  [==[/Users/Nyamerka/VS Code Projects/C++/OOP/lab2/tests]==] [==[--gtest_filter=FourOperators.Plus]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[FourOperators.Plus]=]  PROPERTIES WORKING_DIRECTORY [==[/Users/Nyamerka/VS Code Projects/C++/OOP/lab2]==] SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[FourOperators.Minus]=]  [==[/Users/Nyamerka/VS Code Projects/C++/OOP/lab2/tests]==] [==[--gtest_filter=FourOperators.Minus]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[FourOperators.Minus]=]  PROPERTIES WORKING_DIRECTORY [==[/Users/Nyamerka/VS Code Projects/C++/OOP/lab2]==] SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[FourOperators.IfMore]=]  [==[/Users/Nyamerka/VS Code Projects/C++/OOP/lab2/tests]==] [==[--gtest_filter=FourOperators.IfMore]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[FourOperators.IfMore]=]  PROPERTIES WORKING_DIRECTORY [==[/Users/Nyamerka/VS Code Projects/C++/OOP/lab2]==] SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[FourOperators.IfLess]=]  [==[/Users/Nyamerka/VS Code Projects/C++/OOP/lab2/tests]==] [==[--gtest_filter=FourOperators.IfLess]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[FourOperators.IfLess]=]  PROPERTIES WORKING_DIRECTORY [==[/Users/Nyamerka/VS Code Projects/C++/OOP/lab2]==] SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[FourOperators.IfEqual]=]  [==[/Users/Nyamerka/VS Code Projects/C++/OOP/lab2/tests]==] [==[--gtest_filter=FourOperators.IfEqual]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[FourOperators.IfEqual]=]  PROPERTIES WORKING_DIRECTORY [==[/Users/Nyamerka/VS Code Projects/C++/OOP/lab2]==] SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[FourPrint.DefaultPrint]=]  [==[/Users/Nyamerka/VS Code Projects/C++/OOP/lab2/tests]==] [==[--gtest_filter=FourPrint.DefaultPrint]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[FourPrint.DefaultPrint]=]  PROPERTIES WORKING_DIRECTORY [==[/Users/Nyamerka/VS Code Projects/C++/OOP/lab2]==] SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set(  tests_TESTS FourInitialize.Constructor FourInitize.InitializerListConstructorCorrect FourOperators.Plus FourOperators.Minus FourOperators.IfMore FourOperators.IfLess FourOperators.IfEqual FourPrint.DefaultPrint)
