add_test([=[test1.constructor]=]  [==[/Users/Nyamerka/VS Code Projects/C++/OOP/lab6/tests]==] [==[--gtest_filter=test1.constructor]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[test1.constructor]=]  PROPERTIES WORKING_DIRECTORY [==[/Users/Nyamerka/VS Code Projects/C++/OOP/lab6]==] SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[test2.constructor]=]  [==[/Users/Nyamerka/VS Code Projects/C++/OOP/lab6/tests]==] [==[--gtest_filter=test2.constructor]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[test2.constructor]=]  PROPERTIES WORKING_DIRECTORY [==[/Users/Nyamerka/VS Code Projects/C++/OOP/lab6]==] SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[test3.constructor]=]  [==[/Users/Nyamerka/VS Code Projects/C++/OOP/lab6/tests]==] [==[--gtest_filter=test3.constructor]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[test3.constructor]=]  PROPERTIES WORKING_DIRECTORY [==[/Users/Nyamerka/VS Code Projects/C++/OOP/lab6]==] SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[test4.fight]=]  [==[/Users/Nyamerka/VS Code Projects/C++/OOP/lab6/tests]==] [==[--gtest_filter=test4.fight]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[test4.fight]=]  PROPERTIES WORKING_DIRECTORY [==[/Users/Nyamerka/VS Code Projects/C++/OOP/lab6]==] SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[test5.fight]=]  [==[/Users/Nyamerka/VS Code Projects/C++/OOP/lab6/tests]==] [==[--gtest_filter=test5.fight]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[test5.fight]=]  PROPERTIES WORKING_DIRECTORY [==[/Users/Nyamerka/VS Code Projects/C++/OOP/lab6]==] SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[test6.fight]=]  [==[/Users/Nyamerka/VS Code Projects/C++/OOP/lab6/tests]==] [==[--gtest_filter=test6.fight]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[test6.fight]=]  PROPERTIES WORKING_DIRECTORY [==[/Users/Nyamerka/VS Code Projects/C++/OOP/lab6]==] SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[test7.fight]=]  [==[/Users/Nyamerka/VS Code Projects/C++/OOP/lab6/tests]==] [==[--gtest_filter=test7.fight]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[test7.fight]=]  PROPERTIES WORKING_DIRECTORY [==[/Users/Nyamerka/VS Code Projects/C++/OOP/lab6]==] SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set(  tests_TESTS test1.constructor test2.constructor test3.constructor test4.fight test5.fight test6.fight test7.fight)
